[project]
name = "th2forecast"
description = "Framework for the forecasting models"

[dependencies]
anomalize = "*"
base64enc = "*"
bizdays = "*"
caTools = "*"
caret = "*"
changepoint = "*"
dplyr = "*"
echarts4r = "*"
janitor = "*"
jsonlite = "*"
knitr = "*"
lubridate = "*"
modeltime = "*"
"modeltime.ensemble" = "*"
"modeltime.resample" = "*"
naniar = "*"
plumber2 = "*"
prophet = "*"
recipes = "*"
rmarkdown = "*"
rsample = "*"
sparklyr = "*"
tidymodels = "*"
tidyr = "*"
tidyverse = "*"
timetk = "*"
tsoutliers = "*"
tune = "*"
"apowerb.th2forecast" = "*"

[dev-dependencies]
knitr = "*"
rmarkdown = "*"
