

## KPI analysis: TARGET_KPI

------------------------------------------------------------------------

```{r, echo=FALSE, warning=FALSE, message=FALSE}
table_accuracy <-- data.frame()

data_filter <- params$data %>%
  dplyr::filter(params$data[[params$column_kpi]] == "TARGET_KPI")

result_test_report <- th2forecast::th2_rolling_forecast_stablizer(data_filter, params$var_date, params$var_target, params$column_kpi, params$models, params$split_date, params$horizon)

results_table <<- rbind(results_table, result_test_report$accuracy_df)

list_models <- c(params$models, "TH2ENSEMBLE")

```

```{r, results='asis', echo=FALSE, warning=FALSE, message=FALSE}
for (model in list_models) {
  
  if (model == "lr"){
    model <- "lm"
  }
  
  if(model == "mars"){
      model <- "earth"
  }

  cat(" \n\n")
  cat(paste0("## ", gsub("_", " ", sub("^.", toupper(substr(model, 1, 1)), model)), "\n\n"))
  
  models_upper <- gsub("_", "", toupper(model))

  cat(paste0( gsub("_", " ", sub("^.", toupper(substr(model, 1, 1)), model)), " model evaluation metrics with incremental days per iteration:" , "\n\n"))
  
  # result_test_report <- th2forecast::th2_rolling_forecast_stablizer(data_filter, model)
  
  if (model != list_models[length(list_models)]){
    table_acc <- DT::datatable(result_test_report$accuracy_df %>% 
                                 dplyr::filter(`model_desc` == models_upper)%>%
                                 dplyr::select(-c(mae, rmse, rsq)) %>%
                                 dplyr::rename(mae = test_mae, rmse = test_rmse, rsq = test_rsq)
                               )
    print(htmltools::tagList(table_acc))
    # cat(tests$accuracy_df %>%
    #   knitr::kable("pipe") %>%
    #   kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")))
    
    
    cat("### Results:\n\n")
    cat("comparison of results\n\n")
    
    # cat(tests$time_series_plot)
    plot_test <- result_test_report$time_series_plots[["TARGET_KPI"]][[model]]
    print(htmltools::tagList(plot_test))
    cat("_______\n\n")
    cat("------------------------------------------------------------------------ \n\n")
  }
  table_accuracy <- rbind(table_accuracy, result_test_report$accuracy_df %>% dplyr::filter(`model_desc` == models_upper))
  
}
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
# reult_forecast_arima <- th2forecast::th2_rolling_forecast_stablizer(data_filter, "arima")
result_test_report$accuracy_df %>%
  dplyr::filter(`model_desc` == gsub("_", "", toupper(list_models[length(list_models)]))) %>%
  dplyr::select(-c(mae, rmse, rsq)) %>%
  dplyr::rename(mae = test_mae, rmse = test_rmse, rsq = test_rsq) %>%
  DT::datatable()
```

### Results:

comparison of results

```{r, echo=FALSE, warning=FALSE, message=FALSE}
result_test_report$time_series_plots[["TARGET_KPI"]][[list_models[length(list_models)]]]
```

## Comparison {.tabset}
### MAE 
```{r, echo=FALSE, warning=FALSE, message=FALSE}
mae_accuracy <- table_accuracy %>% 
  dplyr::select(period, model_desc, mae, test_mae) %>%
  group_by(period)
  # tidyr::pivot_wider(names_from = .model_desc, values_from = mae)


mae_accuracy <- mae_accuracy %>%
  dplyr::mutate(ranking = rank(mae))
# coparison_chart <- mae_accuracy %>%
#     echarts4r::e_charts(period)

coparison_chart <- mae_accuracy |> 
  echarts4r::group_by(model_desc) |>
  echarts4r::e_chart(period) |>
  echarts4r::e_bar(test_mae, 
        bind = ranking,
        label = list(
          show = TRUE,
          formatter = "{b}",
          position = "outside"
        )
  )

coparison_chart <- coparison_chart %>%
    echarts4r::e_x_axis(name = "Period") %>%
    echarts4r::e_y_axis(name = "Value") %>%
    echarts4r::e_title(text = "Performance model - MAE", top = 0, left = "center") %>%
    # echarts4r::e_tooltip(trigger = "axis") %>%
    echarts4r::e_tooltip(trigger = "axis", formatter = htmlwidgets::JS('
        function (params) {
          let tooltip = `<p style="width: auto;">${params[0].axisValue}</p>`;
          min = Infinity
          min_val = ""
          i = 0
          params.forEach(({ seriesName, marker, value }) => {
                if( parseInt(params[i].name) < min){
                  min = parseInt(params[i].name)
                  min_val = seriesName
                }
                tooltip += `<p style="width: auto; float: center;">${marker} ${seriesName}<span style="float: right;"><strong>${value[1]}</strong></span></p>`;
                i = i + 1
              });
          tooltip += `<hr> <p style="width: auto;"><strong>Best model in training: ${min_val}</strong></p>`;
          
          return tooltip;
            }')) %>%
    echarts4r::e_legend(top = 20, show = TRUE)

coparison_chart

```

### RMSE
```{r, echo=FALSE, warning=FALSE, message=FALSE}

rmse_accuracy <- table_accuracy %>%
  dplyr::select(period, model_desc, rmse, test_rmse) %>%
  group_by(period)
  # tidyr::pivot_wider(names_from = .model_desc, values_from = rmse)
rmse_accuracy <- rmse_accuracy %>%
  dplyr::mutate(ranking = rank(rmse))

# coparison_chart <- rmse_accuracy %>%
#     echarts4r::e_charts(period)

coparison_chart <- rmse_accuracy |> 
  echarts4r::group_by(model_desc) |>
  echarts4r::e_chart(period) |>
  echarts4r::e_bar(test_rmse, 
        bind = ranking,
        label = list(
          show = TRUE,
          formatter = "{b}",
          position = "outside"
        )
  )

coparison_chart <- coparison_chart %>%
    echarts4r::e_x_axis(name = "Period") %>%
    echarts4r::e_y_axis(name = "Value") %>%
    echarts4r::e_title(text = "Performance model - RMSE", top = 0, left = "center") %>%
    # echarts4r::e_tooltip(trigger = "axis") %>%
    echarts4r::e_tooltip(trigger = "axis", formatter = htmlwidgets::JS('
        function (params) {
          let tooltip = `<p style="width: auto;">${params[0].axisValue}</p>`;
          
          min = Infinity
          min_val = ""
          i = 0
          params.forEach(({ seriesName, marker, value }) => {
                if( parseInt(params[i].name) < min){
                  min = parseInt(params[i].name)
                  min_val = seriesName
                }
          
                tooltip += `<p style="width: auto; float: center;">${marker} ${seriesName}<span style="float: right;"><strong>${value[1]}</strong></span></p>`;
                
                i = i + 1
              });
          tooltip += `<hr> <p style="width: auto;"><strong>Best model in training: ${min_val}</strong></p>`;
          
          return tooltip;
            }')) %>%
    echarts4r::e_legend(top = 20, show = TRUE)

coparison_chart

```

### RSQ
```{r, echo=FALSE, warning=FALSE, message=FALSE }
rsq_accuracy <- table_accuracy %>%
  dplyr::select(period, model_desc, rsq, test_rsq) %>%
  group_by(period)
  # tidyr::pivot_wider(names_from = .model_desc, values_from = rsq) %>%
  # dplyr::mutate(ranking = "")

rsq_accuracy <- rsq_accuracy %>%
  # dplyr::mutate(ranking = rank(rsq))
  dplyr::mutate(ranking = n() - rank(rsq) + 1)

# list_ranks <- list()
# for (i in 1:nrow(rsq_accuracy)) {
#   ranking_accu <- rank(rsq_accuracy[i, 3: (ncol(rsq_accuracy)-1)])
#   
#   list_ranks <- c(list_ranks, list(ranking_accu))
# }
# 
# rsq_accuracy$ranking <- list_ranks
# View(rsq_accuracy)
# View(rsq_accuracy)

# coparison_chart <- rsq_accuracy %>%
#     echarts4r::e_charts(period)

coparison_chart <- rsq_accuracy |> 
  echarts4r::group_by(model_desc) |>
  echarts4r::e_chart(period) |>
  echarts4r::e_bar(test_rsq, 
        bind = ranking,
        label = list(
          show = TRUE,
          formatter = "{b}",
          position = "outside"
        )
  )

coparison_chart <- coparison_chart %>%
    echarts4r::e_x_axis(name = "Period") %>%
    echarts4r::e_y_axis(name = "Value") %>%
    echarts4r::e_title(text = "Performance model  - RSQ", top = 0, left = "center") %>%
    # echarts4r::e_tooltip(trigger = "axis") %>%
    echarts4r::e_tooltip(trigger = "axis", formatter = htmlwidgets::JS('
      function (params) {
        let tooltip = `<p style="width: auto;">${params[0].axisValue}</p>`;
        
        min = Infinity
        min_val = ""
        i = 0
        params.forEach(({ seriesName, marker, value }) => {
              if( parseInt(params[i].name) < min){
                  min = parseInt(params[i].name)
                  min_val = seriesName
              }
              tooltip += `<p style="width: auto; float: center;">${marker} ${seriesName}<span style="float: right;"><strong>${value[1]}</strong></span></p>`;
              
              i = i + 1
            });
        tooltip += `<hr> <p style="width: auto;"><strong>Best model in training: ${min_val}</strong></p>`;
        
        return tooltip;
          }')) %>%
    echarts4r::e_legend(top = 20, show = TRUE)

coparison_chart

```

```{r}
list_kpis <<- c(list_kpis, "TARGET_KPI")

cat("lista de KPIs para la table de performance")
cat(list_kpis)
```

