# This is a basic workflow to help you get started with Actions
name: Test R package RPACKAGENAME
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  build:
    name: Test RPACKAGENAME package
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Use Dockerfile to run unit tests
      run: |
        docker build -f Dockerfile .
